version: '3.4'

services:
  client:
    image: client
    build:
      context: VideosMern_frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
